# Generated by Django 3.1.7 on 2021-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('Job_Name', models.TextField(db_column='Job Name')),
                ('Job_Type', models.CharField(db_column='Job Type', max_length=50)),
                ('Job_Code', models.IntegerField(db_column='Job Code', max_length=7, primary_key=True, serialize=False)),
                ('Salary', models.CharField(db_column='Salary', max_length=10)),
                ('Requirements', models.TextField(db_column='Requirements')),
                ('Experience', models.TextField(db_column='Experience')),
            ],
        ),
    ]
