# Generated by Django 3.1.7 on 2021-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('User_Name', models.TextField(db_column='User Name', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='First Name', max_length=30)),
                ('Last_Name', models.CharField(db_column='Last Name', max_length=30)),
                ('Email', models.EmailField(db_column='Email', max_length=250)),
                ('Phone_Number', models.IntegerField(db_column='Phone Number')),
                ('Password', models.CharField(db_column='Password', max_length=50)),
                ('Password_confirmation', models.CharField(db_column='Password Confirmation', max_length=50)),
                ('Profession', models.CharField(db_column='Profession', max_length=30)),
                ('Age', models.IntegerField(db_column='Age')),
                ('Address', models.CharField(db_column='Address', max_length=30)),
            ],
        ),
    ]
