# Generated by Django 3.1.7 on 2021-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0003_auto_20210404_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
