# Generated by Django 3.1.7 on 2021-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0010_userreg_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
