# Generated by Django 3.1.7 on 2021-04-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0012_userreg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='user',
        ),
    ]
