# Generated by Django 3.1.7 on 2021-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0013_remove_userreg_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='username',
            new_name='user_name',
        ),
    ]
