# Generated by Django 3.1.7 on 2021-04-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_users', '0015_auto_20210408_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(db_column='Company Name', max_length=50)),
                ('Title', models.CharField(db_column='Title', max_length=50)),
                ('Work_Type', models.CharField(db_column='Work Type', max_length=50)),
                ('Description', models.CharField(db_column='Description', max_length=100)),
                ('Requirements', models.CharField(db_column='Requirements', max_length=100)),
                ('Experience', models.CharField(db_column='Experience', max_length=500)),
                ('Salary', models.IntegerField(db_column='Salary', max_length=30)),
                ('Location', models.CharField(db_column='Location', max_length=100)),
                ('Vacancy', models.CharField(db_column='Vacancy', max_length=10)),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to='site_users.profile')),
            ],
        ),
    ]
